### ISSUE TITLE
How to offset query?

### ISSUE THREAD

**Issue by omearamike** [AlJohri/craigslist#8]
Hey not sure if this is a question or an issue. But is it possible to pass in an offset parameter so the entire record range can be returned. I can see that in the init.py script it is set as offset=0 as the default. 

But is it possible to change this using the module interface?

Cheers,
            Mike :)

**Comment by omearamike** [comment]
Also great package btw really well written. Learned so much looking at your code. 👍

**Comment by AlJohri** [comment]
Thanks for the kind words @omearamike!

https://github.com/AlJohri/craigslist/blob/7f31dfa303639a0e4107b8d71183045e3cdb6da8/craigslist/_search/regularsearch.py#L82-L100

Looks like `offset` starts at 0 (first page) and then goes from `100` to `num_total_posts` in steps of `100`. So the "entire record range" should be returned with this function.

Which function are you trying to use?

**Comment by omearamike** [comment]
Ok cool.
The query I am using is below. However it is only returning 119 records by default which is one record short of the default 120 listings per page. A doing a manual search with the below critera it appears that there are over 3000 listings in total spread over 25 pages.

`data = craigslist.search('vancouver', 'apa')`

Let me know if I am doing some thing wrong. 

Cheers Mike :)

**Comment by AlJohri** [comment]
@omearamike  I was mistaken earlier. The package uses `jsonsearch` by default instead of `regularsearch`. Seems like craigslist now requires adding the `?map=1` parameter. Should be fixed now: https://github.com/AlJohri/craigslist/commit/1256181608136c8dfae9fe01c6992e2a5a961b9e

Update the package and try again. You can also try passing in `type_="regularsearch"` to the `search` method and compare the results.

**Comment by omearamike** [comment]
Yes thats getting nearly all the posts now. as you can see it is now returning `3480 posts.` However it seems that the offset is causing an issue I think see below error. I think it might be due to the modulus of post on the last page `< 100`. 

```
3480 :  RegularSearchPost(id=6860878825, title='**THE PRESCOTT - 12th floor - HEAT INCLUDED - AMAZING VIEW 2Bed 2 Bath', url='https://vancouver.craigslist.org/nvn/apa/d/north-vancouver-the-prescott-12th-floor/6860878825.html', repost_id=5554000733, price=3150, bedrooms=2, date='2019-04-10T06:02:00+00:00', area=940) 

Traceback (most recent call last):
  File "main.py", line 7, in <module>
    for i in data:
  File "/Users/michaelomeara/Documents/Projects/2019/Accomodation_Tracker/craigslist-python-wrapper/craigslist/_search/regularsearch.py", line 99, in regularsearch
    num_posts_on_page = get_number_of_posts_on_current_page_from_response(doc)
  File "/Users/michaelomeara/Documents/Projects/2019/Accomodation_Tracker/craigslist-python-wrapper/craigslist/_search/regularsearch.py", line 26, in get_number_of_posts_on_current_page_from_response
    return int(doc.cssselect("#searchform span.pagenum span.rangeTo")[0].text)
IndexError: list index out of range
```

No worries if you don't have time to look at this. 👀
I might try to have a look at it myself. 

Btw would you have any recommendations for material/resources for developing ones programming skills? 👍🏼Your code is very understandable and readable. 

Mike

**Comment by AlJohri** [comment]
@omearamike fixed. it was assuming 100 per page before. https://github.com/AlJohri/craigslist/commit/f85d951b23b3cac28f19a79defe99abcf99dfccc

I believe `jsonsearch` returns more results.

```bash
craigslist search vancouver apa --method regularsearch --verbose | tee test1.json
craigslist search vancouver apa --method jsonsearch --verbose | tee test2.json
```

```bash
$ wc -l test1.json
3000 test1.json
$ wc -l test2.json
9646 test2.json
```

Try version 0.1.9.

**Comment by AlJohri** [comment]
Bump @omearamike - let me know if this is fixed. Thanks!
