### ISSUE TITLE
Apartments sometimes show an availability date

### ISSUE THREAD

**Issue by jbschooley** [AlJohri/craigslist#9]
No idea how long this has been around, but on some posts it says "available xxx date" under the map and next to the bedrooms/bathrooms. This wrapper so far doesn't have a way to parse that. Other than that, amazing work!

**Comment by AlJohri** [comment]
@jbschooley Thanks! Can you send a link or screenshot. Will take a look when I get a chance.

**Comment by jbschooley** [comment]
[This one](https://eastidaho.craigslist.org/roo/d/idaho-falls-bomb-ass-room-for-rent/6861265363.html) is available now (just a room not an apartment so it's on /roo instead of /apa) and [this one](https://eastidaho.craigslist.org/apa/d/idaho-falls-2-bed-1-bath-apartment/6872873348.html) is available may 17

**Comment by jbschooley** [comment]
Any progress on this?
